### ISSUE TITLE
Complete java failure

### ISSUE THREAD

**Issue by Usalabs** [hdecarne/certmgr#7]
This is what happens when running the certmgr.exe file:-

java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at de.carne.certmgr.CertMgrMain.run(CertMgrMain.java:54)
	at de.carne.boot.Application.main(Application.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

And I'm using JDK 8, I tried with JDK 11, JDK 19 and JRE 8, same errors.

The exe file I downloaded is version 1.1.3 x64 windows version.

**Comment by hdecarne** [comment]
JavaFX is missing.
What JDK do you use?
Oracle JDK 8 (as well as 9, 10 to my knowledge) include JavaFX.
OpenJDK for example does not and you have to install JavaFX separately.

**Comment by Usalabs** [comment]
> JavaFX is missing. What JDK do you use? Oracle JDK 8 (as well as 9, 10 to my knowledge) include JavaFX. OpenJDK for example does not and you have to install JavaFX separately.

I tried it with JDK 8.

java -version:-

java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b25, mixed mode)

none of the JDK's I install actually show as java(TM) JDK, they all say SE Runtime Environment.

**Comment by hdecarne** [comment]
In your script the JAVA_HOME variable is made permanent, but not the PATH. I guess, this still leads to an unexpected JRE used when starting CertMgr.

To make sure it is generally working, can you please try to start CertMgr as follows:

Open cmd.exe and make sure you have the desired JRE activated (e.g. by your script or starting it explicitly from its installation path).
The start CertMgr by invoking javaw (or java) with the jar command.
For example, by using the Oracle JDK/JRE 8-341, I can start CertMgr as follows:
```
C:\Users\myuser>java -version
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

C:\Users\myusers>javaw -jar "C:\Program Files\certmgr\certmgr-boot-1.1.3.jar"
```

**Comment by Usalabs** [comment]
If I set the path permanent using setx, I get 6 copies of the same path where java resides, 6 repeated values held in JAVA_HOME, but only applying the path to my user account I only get the one path value inserted.

I uninstalled all but java JRE version "1.8.0_351", and there is no value for JAVA_HOME or JAVA, nor is there a path to java in the path variable, but windows still finds java:-

`C:\Users\Usalabs>java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)`

I tried your suggestion about running certmgr-boot-1.1.3.jar and it does open the certificate store management window.

**Comment by hdecarne** [comment]
The layout issue is tracked via #8.
